### ISSUE TITLE
Need to show a pop up on login page 

### ISSUE THREAD

**Issue by fahadwajed** [NerdCats/T-Rex#13]
If Login fails a pop up should tell why it failed. For example username is wrong or password is wrong it should say that "username or password is incorrect". Because right now it's kinda confusing and irritating that there is no way to know what went wrong.

**Comment by tareq89** [comment]
thanks, will look into it shortly!

**Comment by thehoneymad** [comment]
It's always good to give a story, a result and a expected result section when you guys report an issue.

### Background
Shit happened
###Expected Result
No Shit
###Result
this shit

**Comment by tareq89** [comment]
completed
